GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.1
  visualize_potential: false
  use_dijkstra: false # USE A*
  use_quadratic: true
  use_grid_path: false # TESTER LA PERFORMANCE AVEC TRUE
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3.0
  publish_potential: true




